### PR TITLE
chore: setup repo

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by himorin** [comment]
@marcoscaceres why moving CONTRIBUTING.md and CODE_OF_CONDUCT.md into .github directory?

**Comment by marcoscaceres** [comment]
Github automatically picks those up from .github and does integration with them. It also cleans up the root directory a bit.

**Comment by himorin** [comment]
@marcoscaceres No. These are required files for organization, even if it's IWCG. Refer other repositories like [webxr](https://github.com/immersive-web/webxr) for what is mandatory per W3C regulation.

**Comment by marcoscaceres** [comment]
oh, ok. No problem. Will move them to the root.

**Comment by marcoscaceres** [comment]
Done.

**Pull request merged**
