### PR TITLE
chore(README): add Marcos as contact + update links

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@cabanier @AdaRoseCannon, could you kindly also grant me admin (or similar) rights over this repo? Then I can set up some automation stuff, etc.

**Comment by cabanier** [comment]
> @cabanier @AdaRoseCannon, could you kindly also grant me admin (or similar) rights over this repo? Then I can set up some automation stuff, etc.

I don't have admin right. Maybe @himorin can do this?

**Comment by himorin** [comment]
> > @cabanier @AdaRoseCannon, could you kindly also grant me admin (or similar) rights over this repo? Then I can set up some automation stuff, etc.
> 
> I don't have admin rights. Maybe @himorin can do this?

I suppose they haven't accepted or take action on invitation to organization team. I've re-run script to sync w3c and immersive-web for WG/CG.

**Comment by cabanier** [comment]
> > > @cabanier @AdaRoseCannon, could you kindly also grant me admin (or similar) rights over this repo? Then I can set up some automation stuff, etc.
> > 
> > 
> > I don't have admin rights. Maybe @himorin can do this?
> 
> I suppose they haven't accepted or take action on invitation to organization team. I've re-run script to sync w3c and immersive-web for WG/CG.

Are you saying the @marcoscaceres needs to be invited (or sent an invitation) to the working group?

**Comment by himorin** [comment]
No. this repository is under CG, and we are operating one team in immersive-web github organization whose members are synced to W3C participants' database. But one need to take an action to accept invitation from github for joining to that team. (as for now, 7 for WG and 20 for CG remains as pending invitation to team, which expires after 15 or 30 days from manual operation to sync.)
So, take actions by themselves! ;)

**Comment by marcoscaceres** [comment]
@marcoscaceres action taken, but I'm still not seeing the "Setting" option for the repo. Be great if I could get some privilege elevation then I don't need to ping people to change things 🙏 (promise I'll be good 😜)

**Comment by himorin** [comment]
@marcoscaceres please explain a list of what setting you need.

**Comment by marcoscaceres** [comment]
Well, for instance, the ability to set secret variables. Give a collaborator special abilities. Control the branches and set various CI checks. And control github actions.

**Comment by himorin** [comment]
- the ability to set secret variables: ask each time
- Give a collaborator special abilities: impossible per W3C regulation
- Control the branches (rules) and set various CI checks: ask each time
- And control github actions: you can add by adding relevant files, if fail ask each time

**Comment by marcoscaceres** [comment]
Why tho? I'm in full control of other repos I work on at the w3c? Seem pretty annoying (for you and I) to have to ask.

**Comment by himorin** [comment]
- If pointed some is in [w3c organization](https://github.com/w3c), please let me know.
- If some repository in immersive-web organization, I've not performed mass cleanup yet over old configurations of repositories, so some old group permissions could remain.
- For other github organizations specific to dedicated group, group might not take action to adopt recent regulation.

**Comment by marcoscaceres** [comment]
I'm not following? There is no rigid requirement that editors don't have control over their repositories. I think there might be some confusion here. Certainly, in my last 8 years as a spec editor working on GitHub I've **always** had control over my repos (and would be pretty upset if that was taken away).   

Cc @plehegar. 

Can we kindly not go around in circles about this? I'm not asking for anything out of the ordinary.

**Comment by plehegar** [comment]
catching up here. if @marcoscaceres wants to help on a repository, that's always a wonderful news. So, as long as the CG Chairs and editors are ok, I always highly support to @marcoscaceres .

**Comment by cabanier** [comment]
> catching up here. if @marcoscaceres wants to help on a repository, that's always a wonderful news. So, as long as the CG Chairs and editors are ok, I always highly support the work that @marcoscaceres is willing to do.

The issue is that nobody on the immersive group has admin right, only the W3C staff have.
So it's not up to the chairs and editors to approve this but the W3C.

**Comment by plehegar** [comment]
> The issue is that nobody on the immersive group has admin right, only the W3C staff have. So it's not up to the chairs and editors to approve this but the W3C.

Thanks for pointing this out. That seems broken indeed.

We don't automatically give admin rights to WG Chairs or Editors to REC-track repos unless we're confident they know what they're doing (such as, not deleting the repo by mistake :).

I guess part of the issue here might be that we're mixing CG and WG repositories. Nevertheless, at the minimum, we ought to give admin access to CG repos to the CG Chairs (they can then figure out for the rest as needed).
 
Btw, the W3C Staff in general does not have admin rights over github.com/immersive-web. Only @dontcallmedom (historical reasons I presume) and @himorin have. @w3cbot also has it but we don't use that account to mess around with repos.

**Comment by marcoscaceres** [comment]
@himorin, [given the above](https://github.com/immersive-web/model-element/pull/6#issuecomment-1199778585), could you kindly please grant myself and the Chairs admin rights over this repo? it might be good to give the Chairs admin rights over https://github.com/immersive-web also, as a backup. 

Thanks in advance!

**Comment by marcoscaceres** [comment]
@himorin ping regarding https://github.com/immersive-web/model-element/pull/6#issuecomment-1200598650 🙏

**Pull request merged**
