### PR TITLE
chore: update front matter

### PR DESCRIPTION
**Pull request by zachernuk**
* Retire Marcos and add Zachernuk
* added AOUSD as a localBiblio

***
<a href="https://pr-preview.s3.amazonaws.com/zachernuk/model-element/pull/80.html" title="Last updated on Apr 19, 2024, 10:13 PM UTC (56fa4b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/immersive-web/model-element/80/ed579b5...zachernuk:56fa4b5.html" title="Last updated on Apr 19, 2024, 10:13 PM UTC (56fa4b5)">Diff</a>

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]
LGTM!!!

**Comment by marcoscaceres** [comment]
@AdaRoseCannon, do you have admin over this repo? Can you give @zachernuk write/admin?

**Comment by cabanier** [comment]
> @AdaRoseCannon, do you have admin over this repo? Can you give @zachernuk write/admin?

I think only @himorin can do that.

**Comment by marcoscaceres** [comment]
Ok, no problem. Thanks @cabanier.

**Comment by AdaRoseCannon** [comment]
I do have admin since it is in the CG, I've added @zachernuk as `maintain`

**Comment by himorin** [comment]
> @AdaRoseCannon, do you have admin over this repo? Can you give @zachernuk write/admin?

added to spec-editors, used for CG repository admin.
@zachernuk , could you link your github account at [your W3C profile page](https://www.w3.org/users/94584/connectedaccounts/)?

**Pull request merged**
